name: multi_game_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  blur: ^3.1.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  flutter_blur: ^0.0.2
  flutter_staggered_animations: ^1.1.1
  image_gallery_saver_plus: ^4.0.1
  qr_flutter: ^4.1.0
  provider: ^6.1.5
  web_socket_channel: ^3.0.3
  shelf: ^1.4.1
  shelf_static: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/'

  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/Hardpixel.OTF
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf

